### ISSUE TITLE
About the method of computing BLEU

### ISSUE THREAD

**Issue by whr94621** [JunjieHu/dali#1]
Hi, I notice that when you use `scripts/translate.sh` to evaluate model, you do not use option `--sacrebleu`. Does it mean that <unk> is not accounted in BLEU computation? Do all the values in the paper is computed as the same way as this codebase does ?
Thank you.

**Comment by JunjieHu** [comment]
Sorry for the late response. All the scores in the paper are computed using Moses multi-bleu.perl script (https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl). The scripts/translate.sh in this repo is used as a demo.
