### ISSUE TITLE
Explaining the dataset files

### ISSUE THREAD

**Issue by jayelm** [JunjieHu/dali#2]
Hi, can you explain what the dataset files mean? in particular I'm not sure about the difference between `bpe.clean.en` and `bpe.en` (and why `clean` exists only for the training splits)

**Comment by JunjieHu** [comment]
Hi @jayelm  The `bpe.clean.{de,en}` files are further filtered by the mosedecoder's [clean script](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/training/clean-corpus-n.perl), and the `bpe.{de,en}` files are the original files before filtering. This is the [conventional practice](http://www.statmt.org/moses/?n=FactoredTraining.PrepareTraining) for only the training set to avoid training on super long sentences or sentence pairs with wired length ratio.

**Comment by jayelm** [comment]
Thanks!
